learning_log/urls.py
from django.conf import settings
from django.conf.urls.static import static


"""
URL configuration for learning_log project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #blog
    path('', include('learning_logs.urls')),
    
    # #nutrition importing
    # path('nutritionApp/', include('nutritionApp.urls')),
    
    #alzheimerModel
    path('alzheimerModel/', include('alzheimerModel.urls')),

    path('users/', include('users.urls')), #will match any URL that starts with users
]


#this urls will be unique to our images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

learning_logs/urls.py
"""Defines URL patterns for learning_logs"""

from django.urls import path, include

from . import views
# from nutritionApp import views

app_name = "learning_logs" #helps Django distinguish this urls.py file from files of the same name in other apps within the project
urlpatterns = [ #list of individual pages that can be accesse from learning_logs app
    #Home Page
    path('', views.index, name='index'),
    
    # Show all topics.
    path('topics/', views.topics, name='topics'),
    
    #Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    #Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),

    #Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

    #Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),


]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users' #helps Django distinguish this urls.py file from files of the same name in other apps within the project ie localhost:8000/users/login
urlpatterns = [
    #Login page
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

    #Logout page
    path('logout/', views.logout_view, name='logout'),

    #Registration page
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# tells Django how to work with the data that will be stored in the app model = class
class Topic(models.Model):
    """a topic we are learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        """Return a string representation of the model"""
        return self.text
        
    
class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    topic_Img = models.ImageField(upload_to='topic_images/')
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
        
    def __str__(self):
        """Return a string representation of the model"""
        return self. text[:50] + "..."

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text'] # only field we want to include in the form is text
        labels = {'text': ''} # tell Django not to generate a label for the text field


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text','topic_Img']
        labels = {'text': '','topic_Img': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})} # override Django's default widget choice for this field; Textarea element is a multi-line text input

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')
#@login_required
def topics(request):
    """Show all topics."""
    # topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context) #context is a dictionary [names to access data: data we sent to template]

#@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries"""
    topic = Topic.objects.get(id=topic_id)
    #Make sure the topic belongs to the current user
    # if topic.owner != request.user:
    #     raise Http404
    entries = topic.entry_set.order_by('-date_added') # -date_added to display most recent entries first
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """"Add a new topic"""
    if request.method != 'POST': #determines if request is GET or POST; GET requests are for reading data, POST requests are for submitting data
        #No data submitted; create a blank form
        form = TopicForm()
    else:
        #POST data submitted; process data
        form = TopicForm(data=request.POST) #we intialize the form with the data entered by the user
        if form.is_valid():
            # new_topic = form.save(commit=False) #create a new topic object and assign it to new_topic without saving it to the database yet
            #new_topic.owner = request.user #set the owner attribute of the new topic object to the current user
            # new_topic.save() #save the new topic object to the database, now that it has an owner attached to it
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics')) #redirects the reader back to the topics page after they submit their topic
    #the reverse function: Django will generate the URL from a named URL pattern
    #Display a blank or invalid form
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """"Add a new entry for a particular topic"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        #No data submitted; create a blank form
        form = EntryForm()
    else:
        #POST data submitted; process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False) #create a new entry object and assign it to new_entry without saving it to the database yet
            new_entry.topic = topic #set the topic attribute of the new entry object to the topic we pulled from the database
            new_entry.save() #save the new entry object to the database, now that it has a topic attached to it
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id])) #reverse() gets URL from a named URL pattern, so Django redirects to the topics page
    #Display a blank or invalid form
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """"Edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # if topic.owner != request.user:
    #     raise Http404

    if request.method != 'POST':
        #Initial request; pre-fill form with the current entry
        form = EntryForm(instance=entry) #instance argument tells Django to create a form prefilled with the information from the existing entry object, which the user will be able to see so they can edit
    else:
        #POST data submitted; process data
        form = EntryForm(instance=entry, data=request.POST) #instance argument tells Django to create a form prefilled with the information from the existing entry object and then update it with any relevant data from request.POST
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id])) #reverse() gets URL from a named URL pattern, so Django redirects to the topics page
    topic_image = Entry.objects.all()

    #Display a blank or invalid form
    context = {'entry': entry, 'topic': topic, 'form': form, 'topic_image': topic_image}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

      {% bootstrap_css %} 
      {% bootstrap_javascript %}
  </head>
  
  <body>
<!-- As a link -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
  
    <div class = "navbar-header">
    <button type = "button" class = "navbar-toggle collapsed" data-toggle = "collapse" data-target = "#navbar" aria-expanded = "false" aria-controls = "navbar">
    </button>
       
    </div>
  <div id="navbar" class="navbar-collapse collapse">
  <ul class="nav navbar-nav">
  <li> <a href= "{%url 'learning_logs:topics' %}"> Topics </a></li>
  <li><a href= "{% url 'learning_logs:index' %}"> Learning Log </a></li>
  <li> <a href= "{%url 'alzheimer-model' %}"> Deep Learning Model </a></li>
{#  <li> <a href= "{%url 'table' %}"> Nutrition Lab </a></li>#}
  </ul>
  
{#    <a class="navbar-brand text-bg-dark" href= "{%url 'users:register' %}"> Register </a>#}
{#      <a class="navbar-brand text-bg-dark" href= "{%url 'alzheimer-model' %}"> Deep Learning Model </a>#}
{#  <a class="navbar-brand text-bg-dark" href= "{%url 'table' %}"> Nutrition Lab </a>#}
      <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %} {# is.authenticated is an attribute, if true, then it will display the message #}
      <li><a>Hello, {{ user.username }}.</a></li>
        <li> <a href="{%  url 'users:logout' %}"> Log out</a></li> 
      {% else %}
          {% comment %} <li> <a href= "{%url 'users:register' %}"> Register </a></li> {% endcomment %}
          <li> <a href="{%  url 'users:login' %}">Log in</a></li> 
       {# displays the log in page if they aren't authenticated #}
      {% endif %} 
      </ul>
  </div><!--/.nav-collapse -->
    </div>
</nav>

<!-- As a heading -->

  <div class="container">
      <div class="page-header">
          {% block header %}{% endblock header %}
      </div>
  <div>
        {% block content %}{% endblock content %}
  </div>
     
  </div>




  </body>
</html>
   

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %} 
{% load bootstrap3 %}

{% block header %}
  <h2> Edit entry </h2>
{% endblock header %}

{% block content %}
    <p><a href = "{% url 'learning_logs:topic' topic.id %}"> {{ topic }} </a></p>
    
    <p> Edit entry:</p>
    <form action = "{% url 'learning_logs:edit_entry' entry.id %}" method = 'post' class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-primary">save changes</button>
    {% endbuttons %}
    </form>

    <div class="col-md-4">

                    <img src="{{ entry.topic_Img.url }}" class="img-responsive" style="width: 100%; float: left; margin-right: 10px;" />
            </div>

{% endblock content %}
```

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %} 


{% block header%}
    <div class="jumbotron">
    <h1> Welcome to my portfolio. </h1>
    </div>
    {% endblock header %}

{% block content %}

  <h2> I will list topics of what I am currently learning about relating to Data Science</h2>
      {% comment %} <a href="{% url 'users:register' %}">Register an account</a> to make your own Learning log, list the topics you're learning about, and use the deep learning model.</h2>
     {% endcomment %}

     
    

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %} 
{% load bootstrap3 %}

{% block header %}
  <h2> Add entry </h2>
{% endblock header %}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Add a new entry:</p>
<form action=" {% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">add entry</button>
    {% endbuttons %}

</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %} 
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic: </h2>
{% endblock header %}

{% block content %}

<form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
        <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}

</form>
{% endblock content %}
```

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %} 

{% block header %}
<h2>{{ topic }}</h2>
{% endblock header %}


{% block content %}

<p>Topic: {{ topic }}</p>
    
<p>Entries:</p>
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a>
    </p>


    {% for entry in entries%}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>{{ entry.date_added|date:'M d, Y H:i' }}<small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a></small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks}}

                <img src="{{ entry.topic_Img.url }}" class="img-responsive" style="width: 25%; float: left; margin-right: 10px;" />
            </div>
            {% comment %} <div class="col-md-4">

                    
            </div> {% endcomment %}

            </div>
        
    {% empty%}
        There are no entries for this topic yet.
    {% endfor %}


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %} 


{% block header %}
    <h2>Topics</h2>
{% endblock header %}

{% block content %}



<ul>
    {% for topic in topics %}
        <li>
        <h3><a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic}}</a> </h3>
        </li>
    {% empty%}
        <li> No topics have been added yet. </li>
    {% endfor %}
</ul>
    
   <h3> <a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>
{% endblock content %}